### ISSUE TITLE
Issue with licenses with etherscan-verify

### ISSUE THREAD

**Issue by jab416171** [wighawag/buidler-deploy#29] opened 2020-08-15 00:59 UTC
I believe [this line](https://github.com/wighawag/buidler-deploy/blob/942fc5f4d53a9bc0f75c564631de243e0b6936c0/src/etherscan.ts#L41) in etherscan-verify is only getting the 2nd character of the matched regex, and as a result I get errors like this: 
```license :"N" not supported by etherscan, list of supported license can be found here : https://etherscan.io/contract-license-types . This tool expect the SPDX id, except for "None" and "UNLICENSED"``` when I have a comment like this:
```js
// SPDX-License-Identifier: UNLICENSED
```

**Comment by wighawag** [comment] 2020-08-15 17:06
Thanks for the report. in order to support node 10, I had to switch from native string.matchAll to a matchAll library. This might be the cause of the issue.
Going to look at it

**Comment by wighawag** [comment] 2020-08-16 07:34
fixed in 0.5.15

**Closed by wighawag** 2020-08-16 07:34 UTC
