### ISSUE TITLE
Override of useLiteralContent is problematic

### ISSUE THREAD

**Issue by asselstine** [wighawag/buidler-deploy#26] opened 2020-08-09 00:35 UTC
The line [here](https://github.com/wighawag/buidler-deploy/blob/6774d442badbd3d080d1e4549368f5794b07dd2b/src/index.ts#L92) that overrides the compiler settings `useLiteralContent` results in a error when running buidler `solidity-coverage`.  The error is "InternalCompilerError: Metadata too large.".

For now I've simply set an environment variable and skip loading buidler-deploy when coverage is running, but there must be a more elegant solution.

**Comment by asselstine** [comment] 2020-08-09 00:43
One of my tests used the deploy fixtures, so I couldn't use the environment variable.  But what worked was overriding the override!

My `buidler.config.js` now looks like:

```
usePlugin("buidler-deploy");

// This must occur after buidler-deploy!
task(TASK_COMPILE_GET_COMPILER_INPUT).setAction(async (_, __, runSuper) => {
  const input = await runSuper();
  input.settings.metadata.useLiteralContent = false;
  return input;
})
```

The key here is that the custom override occurs *after* buidler-deploy is loaded!  When the code ran before `usePlugin('buidler-deploy')` it would fail with the `Metadata too large` error.  By moving it *after* the usePlugin it works now.  Hooray!

**Comment by wighawag** [comment] 2020-08-09 07:58
Thanks for reporting. Not sure how to deal with that. Buidler-deploy will
only set metadata literal if not set to something else, but it relies on
metadata literal for etherscan verification.
But it don't think there is a need to change the solc setting when running
test, so maybe it should only do metadata output changw when executing
deploy task

**Comment by asselstine** [comment] 2020-08-09 16:13
That sounds like the right approach.  Only set it to true if verifying contracts.

**Comment by wighawag** [comment] 2020-09-05 20:48
I am going to close it for now. Not sure what I was thinking with my reply. it is important that test run with same setting as deployment. so not going to change the default.
Feel free to reopen if this become an important issue. But maybe the issue is in the solidity-coverage actually

**Closed by wighawag** 2020-09-05 20:48 UTC
